<?php
$flickr_widgets = array(
  'title'       => __('Kemet Flickr', 'kemet-addons' ),
  'classname'   => 'kfw-widget-flickr',
  'id'          => 'kemet-widget-flickr',
  'description' => __('Kemet Flickr', 'kemet-addons' ),
  'fields'      => array(
    array(
      'id'      => 'title',
      'type'    => 'text',
      'title'   => __('Title:', 'kemet-addons' ),
      'default'   => __('Photos from Flickr', 'kemet-addons' ),
    ),
    array(
        'id'      => 'flickr-id',
        'type'    => 'text',
        'title'   => __('Flickr ID', 'kemet-addons' ),
        'subtitle'  =>  __('<a href="' . esc_url( 'http://idgettr.com/' ) . '">Get your flickr ID</a>', 'kemet-addons' ),
      ),
    array(
    'id'    => 'photos-number',
    'type'  => 'number',
    'title' => __('Number of photos to show', 'kemet-addons' ),
    'default'     => 6
    ),
    array(
        'id'      => 'api-key',
        'type'    => 'text',
        'title'   => __('API key', 'kemet-addons' ),
        'subtitle'  =>  __('Get your key from <a href="' . esc_url( 'http://idgettr.com/' ) . '">The App Garden</a>', 'kemet-addons' ),
      ),
)
);

if( ! function_exists( 'kemet_widget_flickr' ) ) {
  function kemet_widget_flickr( $args, $instance ,$id) {
    echo $args['before_widget'];
    if ( ! empty( $instance['title'] ) ) {
      echo $args['before_title'] . apply_filters( 'widget_title', esc_attr($instance['title'], 'kemet-addons' ) ) . $args['after_title'];
    }
    $screen_name = $instance[ 'flickr-id' ];
    $number		 = $instance[ 'photos-number' ];
    $api		 = $instance[ 'api-key' ];
    
    if ( $screen_name && $number && $api ) {
        ?>
        <div class="flickr-images">
            <script type="text/javascript">
                function jsonFlickrApi( rsp ) {
                    if ( rsp.stat != "ok" ) {
                        // If this executes, something broke!
                        return;
                    }

                    //variable "s" is going to contain 
                    //all the markup that is generated by the loop below
                    var s = "";

                    //this loop runs through every item and creates HTML 
                    for ( var i = 0; i < rsp.photos.photo.length; i++ ) {
                        photo = rsp.photos.photo[ i ];

                        //notice that "t.jpg" is where you change the
                        //size of the image
                        t_url = "http://farm" + photo.farm +
                            ".static.flickr.com/" + photo.server + "/" +
                            photo.id + "_" + photo.secret + "_" + "s.jpg";

                        p_url = "http://www.flickr.com/photos/" +
                            photo.owner + "/" + photo.id;

                        s += '<div class="wgt-img flickr_badge_image"><a href="' + p_url + '">' + '<img alt="' +
                            photo.title + '"src="' + t_url + '"/>' + '</a></div>';
                    }

                    document.write( s );
                }
            </script>
            <script type="text/javascript" src="https://api.flickr.com/services/rest/?format=json&amp;method=flickr.photos.search&amp;user_id=<?php echo $screen_name; ?>&amp;api_key=<?php echo $api; ?>&amp;media=photos&amp;per_page=<?php echo $number; ?>&amp;privacy_filter=1"></script>
        </div>
        <?php
    }
    
    echo $args['after_widget']; 
  } 
}

register_widget( Kemet_Create_Widget::instance( "kemet_widget_flickr" , $flickr_widgets) );